begin;

create table if not exists public.daily_motivation_phrases (
  id uuid primary key default gen_random_uuid(),
  phrase text not null unique check (length(trim(phrase)) > 0),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists daily_motivation_phrases_active_sort_idx
  on public.daily_motivation_phrases (is_active, sort_order, created_at);

drop trigger if exists trg_daily_motivation_phrases_updated_at on public.daily_motivation_phrases;
create trigger trg_daily_motivation_phrases_updated_at
before update on public.daily_motivation_phrases
for each row execute function public.set_updated_at();

alter table public.daily_motivation_phrases enable row level security;

drop policy if exists "Public read daily_motivation_phrases" on public.daily_motivation_phrases;
create policy "Public read daily_motivation_phrases"
  on public.daily_motivation_phrases for select
  using (true);

insert into public.daily_motivation_phrases (phrase, sort_order, is_active)
values
('El hierro no tiene piedad.', 1, true),
('Hoy vienes a dominar.', 2, true),
('Tu excusa muere aqui.', 3, true),
('El dolor se arrodilla.', 4, true),
('La disciplina aplasta al miedo.', 5, true),
('No pares hasta imponer respeto.', 6, true),
('Haz que tu cuerpo obedezca.', 7, true),
('Cada repeticion cobra cuentas.', 8, true),
('Aqui se forja el caracter.', 9, true),
('Tu limite llego temprano.', 10, true),
('El cansancio no manda.', 11, true),
('Tu voluntad pesa mas.', 12, true),
('La ferocidad interna gana.', 13, true),
('Suda como si debieras todo.', 14, true),
('Tu mejor version se gana.', 15, true),
('No negocies con la flojera.', 16, true),
('Entrena como si te observaran.', 17, true),
('Rompe la duda en series.', 18, true),
('La constancia destroza al talento.', 19, true),
('Hoy se entrena sin tregua.', 20, true),
('Haz pesado lo que eras.', 21, true),
('No viniste a probar suerte.', 22, true),
('Viniste a imponer disciplina.', 23, true),
('El espejo cobra sacrificio.', 24, true),
('Mueve el peso con hambre.', 25, true),
('El cuerpo escucha a quien manda.', 26, true),
('Tu mente va primero.', 27, true),
('Que tiemble la comodidad.', 28, true),
('La grandeza se repite diario.', 29, true),
('No salgas igual que entras.', 30, true),
('Mas fuerte. Mas frio. Mas duro.', 31, true),
('El esfuerzo deja marca.', 32, true),
('Sudor hoy, respeto despues.', 33, true),
('Cada serie cuenta tu historia.', 34, true),
('La rutina mata la debilidad.', 35, true),
('No aflojes cuando arda.', 36, true),
('Lo dificil tambien se levanta.', 37, true),
('Tu futuro se carga ahora.', 38, true),
('El acero premia la constancia.', 39, true),
('Hazlo aunque no quieras.', 40, true),
('Si duele, controla y sigue.', 41, true),
('Tu cuerpo aun no decide.', 42, true),
('Decides tu. Repite otra vez.', 43, true),
('Vence una excusa por serie.', 44, true),
('Hoy no se pide permiso.', 45, true),
('Haz que esta sesion pese.', 46, true),
('Respira fuego, mueve hierro.', 47, true),
('La flojera tambien se derrota.', 48, true),
('No busques facil, busca cambio.', 49, true),
('Cada gota compra resultados.', 50, true),
('Lo imposible llega cansado.', 51, true),
('Mas orden, mas fuerza.', 52, true),
('Tu hambre vale mas.', 53, true),
('La version debil termina hoy.', 54, true),
('Calla la mente, levanta.', 55, true),
('El cansancio tambien retrocede.', 56, true),
('Tu disciplina da miedo.', 57, true),
('Fuerza sin drama, solo trabajo.', 58, true),
('Entrena hasta convencerte.', 59, true),
('Nada cambia si aflojas.', 60, true),
('Hoy se paga con sudor.', 61, true),
('Cae la excusa, sube el peso.', 62, true),
('Tu energia se construye aqui.', 63, true),
('No naciste para aflojar.', 64, true),
('La incomodidad crea fisico.', 65, true),
('Levanta con orgullo brutal.', 66, true),
('Haz simple lo extraordinario.', 67, true),
('Firme, frio y enfocado.', 68, true),
('Tu cuerpo recuerda todo.', 69, true),
('Cada rep vale respeto.', 70, true),
('Lo que no haces, se nota.', 71, true),
('Hoy toca merecerlo.', 72, true),
('Sin ruido. Solo dominio.', 73, true),
('La fuerza ama a los constantes.', 74, true),
('Tu mente tambien se hipertrofia.', 75, true),
('No te detengas por sentir.', 76, true),
('Todo cambia bajo tension.', 77, true),
('Pelea la ultima repeticion.', 78, true),
('Esta serie define algo.', 79, true),
('Hazlo limpio y feroz.', 80, true),
('El control tambien intimida.', 81, true),
('El trabajo duro deja huella.', 82, true),
('No corras del esfuerzo.', 83, true),
('Si vienes, vienes en serio.', 84, true),
('El gym no regala nada.', 85, true),
('Lo fuerte se construye lento.', 86, true),
('Tu paciencia tambien entrena.', 87, true),
('No busques ganas. Produce accion.', 88, true),
('Hoy mandas tu.', 89, true),
('La barra no escucha excusas.', 90, true),
('Tu nivel sube o miente.', 91, true),
('Cada sesion talla presencia.', 92, true),
('El enfoque tambien levanta.', 93, true),
('Haz mas de lo esperado.', 94, true),
('No aflojes al final.', 95, true),
('La ultima serie desenmascara.', 96, true),
('Mas control, menos pretextos.', 97, true),
('Que el esfuerzo te delate.', 98, true),
('El resultado empieza pesado.', 99, true),
('La constancia cobra musculo.', 100, true),
('El sudor tambien lidera.', 101, true),
('Lo que repites te transforma.', 102, true),
('La fuerza exige presencia.', 103, true),
('Hoy entrenas, no aparentas.', 104, true),
('Tu calma tambien intimida.', 105, true),
('Mueve peso con intencion.', 106, true),
('Cada dia cuenta o resta.', 107, true),
('Sostente. Empuja. Termina.', 108, true),
('El cambio no llega tibio.', 109, true),
('Golpea duro con disciplina.', 110, true),
('No te premies antes.', 111, true),
('Tu version dura te espera.', 112, true),
('Nada grande sale comodo.', 113, true),
('Hoy se entrena con hambre.', 114, true),
('Haz que el cuerpo responda.', 115, true),
('Tu avance no acepta pausa.', 116, true),
('El cansancio se educa.', 117, true),
('Aguanta una serie mas.', 118, true),
('La fuerza respeta al terco.', 119, true),
('No salvas tu orgullo aflojando.', 120, true)
on conflict (phrase) do update
set
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = now();

commit;
